### PR TITLE
Add Aur readme

### PR DESCRIPTION
**Pull request by SuperNici**
Nevermind, ended up adding the arch install instructions anyways. Goodnight.

### CODE REVIEW

**Comment by 7USTIN** [comment]
Thanks again, @SuperNici, for your contribution!

However, I won't merge this because there are two problems:

(1) The script will give an error even if you have 'zathura-pdf-mupdf' installed. This is because the 'check_dependency' function only looks for commands, because there is no universal way to check if a dependency is installed on Linux, and 'zathura-pdf-mupdf' is not a command, so it will throw an error.

(2) I would also like to include 'yay' in the README, as this is also a popular AUR helper.

I hope you understand!

**Comment by SuperNici** [comment]
Ah sure thing, I didn't got that in depth into the source code yet, glad you checked before merging!

**Comment by 7USTIN** [comment]
I just pushed a commit for the README. In the process I had some problems with git and did `git push origin --force`, and now your commit has been removed from the commit history. Sorry about that. I am still a newbie when it comes to git. Lesson learned.

**Comment by SuperNici** [comment]
Haha, no hard feelings, I can (and will) do some more commits in the future. Especially Issue #6 has my attention right now  ;)

**Comment by 7USTIN** [comment]
I'm glad to hear that. I think the same as you do about ani-cli. I'm currently working on solutions for Issue #5 and Issue #6 :)

**Comment by SuperNici** [comment]
Sent a friend request ( ´ ▽ ` )b

**Pull request closed without merging**
